from os import remove, mkdir
from random import choice
from string import ascii_letters


def random_text(num):
    return ''.join(choice(ascii_letters) for x in range(num))


def random_file(name, extension):
    open('created_files/{}.{}'.format(name, extension), 'w').close()


def files_num():
    extension = choice(extensions)
    name = random_text(choice(range(5, 9)))
    file_create_txt(name, extension)
    random_file(name, extension)


def file_create_txt(name, extension):
    with open("created_files.txt", 'a')as cr:
        cr.write('{}.{}\n'.format(name, extension))


def del_created():
    print("[-] Deleting files")
    with open("created_files.txt", 'r')as de:
        for i in de:
            remove('created_files/' + i.strip())
    try:
        remove("created_files.txt")
        remove("created_files")
    except:
        print("[*] Manually delete the created folder")


def main():
    credit()
    try:
        mkdir("created_files")
    except:
        pass
    menu = input("""
                        *************************************
                        *       Menu                        *
                        *************************************
                        *   1. Create files                 *
                        *   2. Delete files                 *
                        *************************************
                        
[+]  Enter your choice :- """)
    if menu == "1":
        fi_num = int(input("[+] Enter number of files to create :- "))
        for i in range(fi_num):
            files_num()
        print("[+] Files created successfully to the folder created_files")
    elif menu == "2":
        del_created()


def credit():
    print("""
           Automatic Random files generator
           """)
    print("""

   ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
  ▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
  ▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
  ▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
  ░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
  ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
    ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
    ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
     ░           ░  ░ ░  ░  ░   ░         ░  ░ code generated by Rahul.p

""")


extensions = ["jpg", "png", "mp4", "mkv", "mp3", "apk", "ts", "zip", "rar"]

try:
    main()
except KeyboardInterrupt:
    print("\n[-] Exiting program")
